name: Main

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Publish
        run: ./node_modules/.bin/auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.KS_BOT_GITHUB_TOKEN_NEW }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
